#!/usr/bin/env php
<?php

declare(strict_types=1);

use WTD\Application\Application;
use WTD\Console\Input;
use WTD\Console\Kernel;
use WTD\Console\Output;
use WTD\Console\UnknownCommandException;

/** @var Application $app */
$app = require __DIR__ . '/bootstrap/app.php';

/** @var Kernel $kernel */
$kernel = $app->container()->get(Kernel::class);
$output = Output::standard();

try {
    exit($kernel->handle(Input::fromArgv($argv), $output));
} catch (UnknownCommandException $exception) {
    $output->error($exception->getMessage());
    exit(1);
}
