#!/usr/bin/env php
<?php

declare(strict_types=1);

use WTD\Application\Application;
use WTD\CLI\CliApplication;
use WTD\Console\Output;

/** @var Application $app */
$app = require __DIR__ . '/bootstrap/app.php';

/** @var CliApplication $cli */
$cli = $app->container()->get(CliApplication::class);
exit($cli->run($argv, Output::standard()));
